import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';
import daisyui from 'daisyui';

const cssColor = (variable) => `rgb(var(${variable}) / <alpha-value>)`;

export default {
    darkMode: 'class',
    content: [
        './app/**/*.php',
        './resources/**/*.blade.php',
        './resources/**/*.js',
    ],
    theme: {
        extend: {
            colors: {
                'on-primary-fixed': cssColor('--color-on-primary-fixed-rgb'),
                'on-primary': cssColor('--color-on-primary-rgb'),
                'secondary-fixed-dim': cssColor('--color-secondary-fixed-dim-rgb'),
                'error-container': cssColor('--color-error-container-rgb'),
                'secondary-dim': cssColor('--color-secondary-dim-rgb'),
                'surface-dim': cssColor('--color-surface-dim-rgb'),
                'on-secondary-container': cssColor('--color-on-secondary-container-rgb'),
                'on-background': cssColor('--color-on-background-rgb'),
                'tertiary-dim': cssColor('--color-tertiary-dim-rgb'),
                'secondary': cssColor('--color-secondary-rgb'),
                'surface-container-highest': cssColor('--color-surface-container-highest-rgb'),
                'inverse-on-surface': cssColor('--color-inverse-on-surface-rgb'),
                'primary': cssColor('--color-primary-rgb'),
                'on-secondary': cssColor('--color-on-secondary-rgb'),
                'background': cssColor('--color-background-rgb'),
                'on-secondary-fixed': cssColor('--color-on-secondary-fixed-rgb'),
                'error-dim': cssColor('--color-error-dim-rgb'),
                'on-tertiary-container': cssColor('--color-on-tertiary-container-rgb'),
                'tertiary-fixed-dim': cssColor('--color-tertiary-fixed-dim-rgb'),
                'on-secondary-fixed-variant': cssColor('--color-on-secondary-fixed-variant-rgb'),
                'on-tertiary-fixed-variant': cssColor('--color-on-tertiary-fixed-variant-rgb'),
                'on-primary-fixed-variant': cssColor('--color-on-primary-fixed-variant-rgb'),
                'surface-container-low': cssColor('--color-surface-container-low-rgb'),
                'outline': cssColor('--color-outline-rgb'),
                'on-primary-container': cssColor('--color-on-primary-container-rgb'),
                'surface-variant': cssColor('--color-surface-variant-rgb'),
                'surface': cssColor('--color-surface-rgb'),
                'on-tertiary': cssColor('--color-on-tertiary-rgb'),
                'primary-container': cssColor('--color-primary-container-rgb'),
                'surface-container-lowest': cssColor('--color-surface-container-lowest-rgb'),
                'tertiary': cssColor('--color-tertiary-rgb'),
                'inverse-primary': cssColor('--color-inverse-primary-rgb'),
                'secondary-fixed': cssColor('--color-secondary-fixed-rgb'),
                'secondary-container': cssColor('--color-secondary-container-rgb'),
                'primary-dim': cssColor('--color-primary-dim-rgb'),
                'error': cssColor('--color-error-rgb'),
                'inverse-surface': cssColor('--color-inverse-surface-rgb'),
                'on-error-container': cssColor('--color-on-error-container-rgb'),
                'on-tertiary-fixed': cssColor('--color-on-tertiary-fixed-rgb'),
                'surface-tint': cssColor('--color-surface-tint-rgb'),
                'surface-container': cssColor('--color-surface-container-rgb'),
                'primary-fixed': cssColor('--color-primary-fixed-rgb'),
                'surface-container-high': cssColor('--color-surface-container-high-rgb'),
                'tertiary-fixed': cssColor('--color-tertiary-fixed-rgb'),
                'primary-fixed-dim': cssColor('--color-primary-fixed-dim-rgb'),
                'on-surface': cssColor('--color-on-surface-rgb'),
                'tertiary-container': cssColor('--color-tertiary-container-rgb'),
                'on-error': cssColor('--color-on-error-rgb'),
                'surface-bright': cssColor('--color-surface-bright-rgb'),
                'outline-variant': cssColor('--color-outline-variant-rgb'),
                'on-surface-variant': cssColor('--color-on-surface-variant-rgb'),
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
            fontFamily: {
                headline: ['Manrope', 'sans-serif'],
                body: ['Inter', 'sans-serif'],
                label: ['Inter', 'sans-serif'],
            },
        },
    },
    plugins: [forms, containerQueries, daisyui],
    daisyui: {
        themes: false,
        logs: false,
    },
};
