<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Mapping Kecamatan -> Kota/Kabupaten -> Provinsi
    |--------------------------------------------------------------------------
    |
    | Digunakan untuk auto-suggest kecamatan serta auto-fill kota dan provinsi.
    | Struktur disimpan flat agar pencarian lebih ringan di frontend.
    |
    */
    'mapping' => [
        'Andir' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Antapani' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Arcamanik' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Astana Anyar' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Babakan Ciparay' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Bandung Kidul' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Bandung Kulon' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Bandung Wetan' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Batununggal' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Bojongloa Kaler' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Bojongloa Kidul' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Buahbatu' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Cibeunying Kaler' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Cibeunying Kidul' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Cibiru' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Cicendo' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Cidadap' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Cinambo' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Coblong' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Gedebage' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Kiaracondong' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Lengkong' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Mandalajati' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Panyileukan' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Rancasari' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Regol' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Sukajadi' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Sukasari' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Sumur Bandung' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Ujungberung' => ['city' => 'Bandung', 'province' => 'Jawa Barat'],
        'Arjasari' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Baleendah' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Banjaran' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Bojongsoang' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Cangkuang' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Cicalengka' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Cikancung' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Cileunyi' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Cimaung' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Cimenyan' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Ciparay' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Ciwidey' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Dayeuhkolot' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Katapang' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Kutawaringin' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Majalaya' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Margaasih' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Margahayu' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Nagreg' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Pacet' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Pameungpeuk' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Pangalengan' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Paseh' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Pasirjambu' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Rancaekek' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Soreang' => ['city' => 'Kabupaten Bandung', 'province' => 'Jawa Barat'],
        'Batujajar' => ['city' => 'Bandung Barat', 'province' => 'Jawa Barat'],
        'Cihampelas' => ['city' => 'Bandung Barat', 'province' => 'Jawa Barat'],
        'Cikalongwetan' => ['city' => 'Bandung Barat', 'province' => 'Jawa Barat'],
        'Cililin' => ['city' => 'Bandung Barat', 'province' => 'Jawa Barat'],
        'Cipatat' => ['city' => 'Bandung Barat', 'province' => 'Jawa Barat'],
        'Cisarua' => ['city' => 'Bandung Barat', 'province' => 'Jawa Barat'],
        'Lembang' => ['city' => 'Bandung Barat', 'province' => 'Jawa Barat'],
        'Ngamprah' => ['city' => 'Bandung Barat', 'province' => 'Jawa Barat'],
        'Padalarang' => ['city' => 'Bandung Barat', 'province' => 'Jawa Barat'],
        'Parongpong' => ['city' => 'Bandung Barat', 'province' => 'Jawa Barat'],
        'Cimahi Selatan' => ['city' => 'Cimahi', 'province' => 'Jawa Barat'],
        'Cimahi Tengah' => ['city' => 'Cimahi', 'province' => 'Jawa Barat'],
        'Cimahi Utara' => ['city' => 'Cimahi', 'province' => 'Jawa Barat'],
        'Bekasi Barat' => ['city' => 'Bekasi', 'province' => 'Jawa Barat'],
        'Bekasi Selatan' => ['city' => 'Bekasi', 'province' => 'Jawa Barat'],
        'Bekasi Timur' => ['city' => 'Bekasi', 'province' => 'Jawa Barat'],
        'Bekasi Utara' => ['city' => 'Bekasi', 'province' => 'Jawa Barat'],
        'Jatiasih' => ['city' => 'Bekasi', 'province' => 'Jawa Barat'],
        'Jatisampurna' => ['city' => 'Bekasi', 'province' => 'Jawa Barat'],
        'Medan Satria' => ['city' => 'Bekasi', 'province' => 'Jawa Barat'],
        'Mustika Jaya' => ['city' => 'Bekasi', 'province' => 'Jawa Barat'],
        'Pondok Gede' => ['city' => 'Bekasi', 'province' => 'Jawa Barat'],
        'Rawalumbu' => ['city' => 'Bekasi', 'province' => 'Jawa Barat'],
        'Bogor Barat' => ['city' => 'Bogor', 'province' => 'Jawa Barat'],
        'Bogor Selatan' => ['city' => 'Bogor', 'province' => 'Jawa Barat'],
        'Bogor Tengah' => ['city' => 'Bogor', 'province' => 'Jawa Barat'],
        'Bogor Timur' => ['city' => 'Bogor', 'province' => 'Jawa Barat'],
        'Bogor Utara' => ['city' => 'Bogor', 'province' => 'Jawa Barat'],
        'Tanah Sareal' => ['city' => 'Bogor', 'province' => 'Jawa Barat'],
        'Beji' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Bojongsari' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Cilodong' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Cimanggis' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Cinere' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Cipayung' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Limo' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Pancoran Mas' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Sawangan' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Sukmajaya' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Tapos' => ['city' => 'Depok', 'province' => 'Jawa Barat'],
        'Cakung' => ['city' => 'Jakarta Timur', 'province' => 'DKI Jakarta'],
        'Ciracas' => ['city' => 'Jakarta Timur', 'province' => 'DKI Jakarta'],
        'Duren Sawit' => ['city' => 'Jakarta Timur', 'province' => 'DKI Jakarta'],
        'Jatinegara' => ['city' => 'Jakarta Timur', 'province' => 'DKI Jakarta'],
        'Kramat Jati' => ['city' => 'Jakarta Timur', 'province' => 'DKI Jakarta'],
        'Makasar' => ['city' => 'Jakarta Timur', 'province' => 'DKI Jakarta'],
        'Pasar Rebo' => ['city' => 'Jakarta Timur', 'province' => 'DKI Jakarta'],
        'Pulo Gadung' => ['city' => 'Jakarta Timur', 'province' => 'DKI Jakarta'],
        'Cengkareng' => ['city' => 'Jakarta Barat', 'province' => 'DKI Jakarta'],
        'Grogol Petamburan' => ['city' => 'Jakarta Barat', 'province' => 'DKI Jakarta'],
        'Kebon Jeruk' => ['city' => 'Jakarta Barat', 'province' => 'DKI Jakarta'],
        'Kembangan' => ['city' => 'Jakarta Barat', 'province' => 'DKI Jakarta'],
        'Palmerah' => ['city' => 'Jakarta Barat', 'province' => 'DKI Jakarta'],
        'Tambora' => ['city' => 'Jakarta Barat', 'province' => 'DKI Jakarta'],
        'Taman Sari' => ['city' => 'Jakarta Barat', 'province' => 'DKI Jakarta'],
        'Cilandak' => ['city' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
        'Jagakarsa' => ['city' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
        'Kebayoran Baru' => ['city' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
        'Kebayoran Lama' => ['city' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
        'Mampang Prapatan' => ['city' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
        'Pancoran' => ['city' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
        'Pasar Minggu' => ['city' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
        'Pesanggrahan' => ['city' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
        'Setiabudi' => ['city' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
        'Tebet' => ['city' => 'Jakarta Selatan', 'province' => 'DKI Jakarta'],
        'Batuceper' => ['city' => 'Tangerang', 'province' => 'Banten'],
        'Cibodas' => ['city' => 'Tangerang', 'province' => 'Banten'],
        'Ciledug' => ['city' => 'Tangerang', 'province' => 'Banten'],
        'Cipondoh' => ['city' => 'Tangerang', 'province' => 'Banten'],
        'Karang Tengah' => ['city' => 'Tangerang', 'province' => 'Banten'],
        'Karawaci' => ['city' => 'Tangerang', 'province' => 'Banten'],
        'Larangan' => ['city' => 'Tangerang', 'province' => 'Banten'],
        'Neglasari' => ['city' => 'Tangerang', 'province' => 'Banten'],
        'Pinang' => ['city' => 'Tangerang', 'province' => 'Banten'],
        'Ciputat' => ['city' => 'Tangerang Selatan', 'province' => 'Banten'],
        'Ciputat Timur' => ['city' => 'Tangerang Selatan', 'province' => 'Banten'],
        'Pamulang' => ['city' => 'Tangerang Selatan', 'province' => 'Banten'],
        'Pondok Aren' => ['city' => 'Tangerang Selatan', 'province' => 'Banten'],
        'Serpong' => ['city' => 'Tangerang Selatan', 'province' => 'Banten'],
        'Serpong Utara' => ['city' => 'Tangerang Selatan', 'province' => 'Banten'],
        'Setu' => ['city' => 'Tangerang Selatan', 'province' => 'Banten'],
    ],
];
